version: "3"
services:
  client:
    image: k4yp/client
    ports:
      - "4173:4173"
    restart: always
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=hello
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dev_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data