version: "3"
services:
  client:
    image: k4yp/client
    ports:
      - "4173:4173"
    restart: always
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      -  postgres_db:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      static-network:
        ipv4_address: 172.20.0.3
  server:
    image: k4yp/server
    ports:
      - "8080:8080"
    restart: always
volumes:
  postgres_db:
    driver: local
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16